[build]
  command = "pnpm install --no-frozen-lockfile && pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NPM_FLAGS = "--prefix"
  PNPM_VERSION = "10.30.3"

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://vishwamitr-api.onrender.com"
